name: xapptor_ui
description: UI Module for a variety of useful Widgets.
# repository: https://github.com/Xapptor/xapptor_ui
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.4

environment:
  sdk: ">=3.1.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  smooth_page_indicator: ^1.2.1
  auto_size_text_pk: ^3.0.0
  uuid: ^4.5.2
  path_provider: ^2.1.5

  font_awesome_flutter: ^10.12.0

  mobile_scanner: ^7.1.3
  permission_handler: ^12.0.1
  google_fonts: ^6.3.2
  animated_text_kit: ^4.3.0
  pdf: ^3.11.3
  printing: ^5.14.2
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0
  universal_platform: ^1.1.0
  intl: ^0.20.2
  url_launcher: ^6.3.2

  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  flutter_downloader: ^1.12.0
  pointer_interceptor: ^0.10.1+2
  shared_preferences: ^2.5.3
  web: ^1.1.1
  video_player: ^2.10.1

  # xapptor_router: ^0.0.2

  xapptor_db:
    path: ../xapptor_db
  xapptor_router:
    path: ../xapptor_router

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/images/

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: FontAwesomeRegular
      fonts:
        - asset: fonts/fa-regular-400.ttf
          weight: 400

    - family: FontAwesomeLight
      fonts:
        - asset: fonts/fa-light-300.ttf
          weight: 300
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
